### ISSUE TITLE
[Feature Request] Group functionality

### ISSUE THREAD

**Issue by martinxxd** [SAP/project-sailor#32]
#### What would you like to be added:
* Provide support for the **Group** entity

#### Why is this needed:
For some Machine Learning use-cases, a Group provides a more flexible way to aggregate equipment. It would be great if that concept could be utilized with Sailor. A Group supports multiple business types such as **Model** or **Equipment**.

##### Group Documentation:
* https://help.sap.com/viewer/4d5ca1b8c320409d961551bc60695e25/2105/en-US/d4f0e0675beb4607bb549888190e8467.html
* https://api.sap.com/api/GroupsAPI/resource

##### Sample:
```python
import pandas as pd
from sailor.assetcentral import find_group, find_equipment, find_notifications

# find group and related equipment
group_set = find_group(name='my_group_name')
equipment_set = group_set.find_equipment()

# find notifications and plot them
notification_set = equipment_set.find_notifications(extended_filters=['malfunction_start_date > "2020-08-01"'])
notification_set.plot_overview()
```

**Comment by atrejut** [comment]
Hi @martinxxd,

thanks for the request. I took a look at the APIs and don't see any fundamental problems, but there are some details here:
- the group API doesn't support server-side filters unfortunately (https://api.sap.com/api/GroupsAPI/resource) so for your `find_group` line above we'd need to fetch all groups and filter client side.
- Groups seem to be pretty complex objects (different group types, allowed business objects depend on group type, and one group may contain business objects of multiple types).  Any special requirements around this? Easiest would probably be to give you access to all business objects of one type in one call (like your `group_set.find_equipment` above returning all equipments but ignoring e.g. locations, and `group_set.find_locations` doing the same for locations in the group).
- since multiple groups make up one `group_set`: would you expect `group_set.find_equipment` to return those equipment that are in *any* of the groups, or those equipment that are in *all* of the groups?

Thanks,

Atreju

**Comment by atrejut** [comment]
Hey @martinxxd 

take a look at the (very much unfinished) branch at https://github.com/sap/project-sailor/tree/feature/groups-support/sailor
I think it should allow the example you give above -- let me know if this matches what you need.

Atreju

**Comment by martinxxd** [comment]
Hi @atrejut,

Awesome, thanks for the quick turnaround! I didn't test your branch yet, but looks like it already covers our use-case.

> * the group API doesn't support server-side filters unfortunately ([api.sap.com/api/GroupsAPI/resource](https://api.sap.com/api/GroupsAPI/resource)) so for your `find_group` line above we'd need to fetch all groups and filter client side.

Oh that's unfortunate. Maybe we can add a method `find_group` to directly resolve a group given it's id, using `/services/api/v1/groups/{id}`.

> * Groups seem to be pretty complex objects (different group types, allowed business objects depend on group type, and one group may contain business objects of multiple types).  Any special requirements around this? Easiest would probably be to give you access to all business objects of one type in one call (like your `group_set.find_equipment` above returning all equipments but ignoring e.g. locations, and `group_set.find_locations` doing the same for locations in the group).

We're currently only utilizing the equipment type. But I think you're right, easiest would probably be to give access to all business objects of one type in one call.

> * since multiple groups make up one `group_set`: would you expect `group_set.find_equipment` to return those equipment that are in _any_ of the groups, or those equipment that are in _all_ of the groups?

I would expect to return equipment that are in _any_ of the groups. Looks like that's also the way you've implemented.
